language: java

jdk: oraclejdk8

sudo: false

addons:
  sonarcloud:
    organization: "ericmuller-github" # the key of the org you chose at step #3
    token:
      secure: 0788142029544ae075cb932452c66ed1167fd5bd # encrypted value of your token

script:
  - mvn clean verify sonar:sonar -Prun-sonar



deploy:
  provider: heroku
  api_key:
    secure: "483d9f20-0dc6-4600-87f7-971de7b1498c"
  app: qcm-rest-api
  on:
    repo: EricMuller/qcm-rest-api

cache:
  directories:
     - '$HOME/.m2'
     - '$HOME/.sonar/cache'
