language: java

jdk: oraclejdk8

sudo: false
script: mvn clean verify

deploy:
  provider: heroku
  api_key:
    secure: "483d9f20-0dc6-4600-87f7-971de7b1498c"
  app: qcm-designer-api
  on:
    repo: EricMuller/qcm-designer-api

