info:
  application-name: qcm-designer-api

logging:
  # file: logs/application-debug.LOGGER
  level:
    root: WARN
    org.springframework.web: ERROR
    org.springframework.security: DEBUG
    org.hibernate: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql: WARN
    com.emu.apps: WARN
    org.keycloak.services: DEBUG
    org.springframework.aop.interceptor.PerformanceMonitorInterceptor: TRACE
    com.zaxxer.hikari.pool.HikariPool: DEBUG
    com.zaxxer.hikari: DEBUG

spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    generate-ddl: false
    show-sql: false
    hibernate:
      id:
        new_generator_mappings: true

  application:
    name: qcm-service
#  liquibase:
#    change-log: classpath:liquibase-changeLog.xml

#
#management:

#    server:
#        context-path: /metrics
#        address: 127.0.0.1
#        port: 9010
#        security:
#            enabled: false
#
#   endpoints:
#       web:
#          exposure:
#              include: "*"
#   endpoint:
#       health:
#          show-details: ALWAYS



