info:
  application-name: qcm-rest-api

logging:
  # file: logs/application-debug.LOGGER
  level:
    root: WARN
    org.springframework.web: ERROR
    org.springframework.security: WARN
    org.hibernate: WARN
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: DEBUG
    com.emu.apps: WARN
    org.keycloak.services: WARN
    org.springframework.aop.interceptor.PerformanceMonitorInterceptor: TRACE
    com.zaxxer.hikari.pool.HikariPool: INFO
    com.zaxxer.hikari: INFO
    org.springframework.boot.web.embedded.tomcat.TomcatWebServer: INFO

spring:
  resources:
    cache:
      period: 31536000
      cachecontrol:
        max-age: 31536000
    chain:
      html-application-cache: true
      enabled: true
      strategy:
        content:
          enabled: true
          paths: /webjars/swagger-ui/**.*

server:
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024
  http2:
    enabled: true
  servlet:
    context-path: /



maven.version: @project.version@
