
---
spring:
    profiles: heroku-postgresql
    jpa:
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        generate-ddl: false
        show-sql: false

        hibernate:
            use-new-id-generator-mappings: true
            ddl-auto: update
            dialect: org.hibernate.dialect.PostgreSQLDialect
            properties:
                 hibernate:
                     enable_lazy_load_no_trans: false
                     generate_statistics: true
                     order_inserts: true
                     order_updates: true
                     jdbc:
                         fetch_size: 100
                         batch_size: 20
                         batch_versioned_data: true

            cache:
                 use_second_level_cache: false
                 use_query_cache: false
                 region:
                     factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory

        properties:
            javax:
                persistence:
                     sharedCache:
                          mode: ENABLE_SELECTIVE

            hibernate:
                current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
                hikari:
                    maximumPoolSize: 30

    datasource:
        type: com.zaxxer.hikari.HikariDataSource
        url: ${DATABASE_URL}
        driverClassName: org.postgresql.Driver
#        username: ${JDBC_DATABASE_USERNAME}
#        password: ${JDBC_DATABASE_PASSWORD}
        hikari:
                url: ${JDBC_DATABASE_URL}
                pool-name: qcm-hikari-pool
                autoCommit: false
                connection-test-query: SELECT 1
                idleTimeout: 20000
                minimum-idle: 1
                maximumPoolSize: 5
